mysite/accounts/urls.py
from django.urls import path

from . import views

# app_name = 'accounts'
urlpatterns = [
	path('signup/', views.signup, name='signup'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from . import views

urlpatterns = [
	path('accounts/', include('accounts.urls')),
	path('accounts/', include('django.contrib.auth.urls')),
	path('', views.home, name='home'),
	# path('<int:post_id>/', views.post, name='post'),
	path('post/', include('post.urls')),
  path('admin/', admin.site.urls),
	
	path('webcam/', include('webcam.urls')),
]

mysite/post/urls.py
from django.urls import path


from . import views

app_name = 'post'
urlpatterns = [
	path('<int:post_id>/', views.post, name='post'),
]

mysite/webcam/urls.py
from django.urls import path
from django.views.generic.base import TemplateView


from . import views

app_name = 'webcam'
urlpatterns = [
	path("", views.webcam, name="webcam"),
]

mysite/accounts/models.py
from django.db import models

# Create your models here.

mysite/post/models.py
from django.db import models

from webcam.models import Post
# Create your models here.
class Comment(models.Model):
	img_id = models.IntegerField()
	login = models.CharField(max_length=255, null=False)
	comment = models.CharField(max_length=255, null=False)
	postdate = models.DateTimeField(auto_now_add=True, null=False)
	post = models.ForeignKey(Post,on_delete=models.CASCADE)


class Like(models.Model):
	img_id = models.IntegerField()
	login = models.CharField(max_length=255, null=False)
	post = models.ForeignKey(Post,on_delete=models.CASCADE)

mysite/webcam/models.py
from django.db import models

# Create your models here.

# django orm auto-generate id as primary key in default
class Post(models.Model):
	login = models.CharField(max_length=255, null=False)
	image = models.CharField(max_length=255, null=False)
	postdate = models.DateTimeField(auto_now_add=True, null=False)

mysite/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from django.core.exceptions import ValidationError
 
 
class CustomUserCreationForm(forms.Form):
    username = forms.CharField(label='Enter Username', min_length=4, max_length=150)
    email = forms.EmailField(label='Enter email')
    password1 = forms.CharField(label='Enter password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirm password', widget=forms.PasswordInput)
 
    def clean_username(self):
        username = self.cleaned_data['username'].lower()
        r = User.objects.filter(username=username)
        if r.count():
            raise  ValidationError("Username already exists")
        return username
 
    def clean_email(self):
        email = self.cleaned_data['email'].lower()
        r = User.objects.filter(email=email)
        if r.count():
            raise  ValidationError("Email already exists")
        return email
 
    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
 
        if password1 and password2 and password1 != password2:
            raise ValidationError("Password don't match")
 
        return password2
 
    def save(self, commit=True):
        user = User.objects.create_user(
            self.cleaned_data['username'],
            self.cleaned_data['email'],
            self.cleaned_data['password1']
        )
        return user

mysite/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from .forms import CustomUserCreationForm
from django.contrib import messages



# Create your views here.

def signup(request):
	if request.method == 'POST':
		f = CustomUserCreationForm(request.POST)
		if f.is_valid():
			f.save()
			messages.success(request, 'Account created successfully')
			return redirect('login')
	else:
		f = CustomUserCreationForm()
	return render(request, 'registration/signup.html', {'form': f})

mysite/mysite/views.py
from django.shortcuts import render
from webcam.models import Post
from django.contrib.auth.models import User
from django.contrib import messages
from post.models import Comment, Like

def home(request):
	if request.method == 'GET':
		posts = Post.objects.all()
		return render(request, 'home.html', {'posts': posts})
	elif request.method == 'POST':
		username = request.user.username
		post_id = int(request.POST.get('post_id'))  
		post = Post.objects.get(id=post_id)
		if username == post.login:
			post.delete()
			posts = Post.objects.all()
			return render(request, 'home.html', {'posts': posts})
		else:
			posts = Post.objects.all()
			return render(request, 'home.html', {'posts': posts})

# def post(request, post_id):
# 	post = Post.objects.get(id=post_id)
# 	return render(request, 'post.html', {'post': post})

mysite/post/views.py
from django.shortcuts import render
from webcam.models import Post
from .models import Comment, Like

from datetime import datetime
# Create your views here.

def post(request, post_id):
	if request.method == 'GET':
		post = Post.objects.get(id=post_id)
		comments = Comment.objects.all()
		likes = Like.objects.all()
		return render(request, 'post.html', {'post': post, 'comments': comments, 'likes': likes})
	elif request.method == 'POST':
		login = request.user.username
		if 'comment_form' in request.POST:
			comment = request.POST.get('comment')
			add_comment(login, post_id, comment)
			likes = Like.objects.all()
			comments = Comment.objects.all()
			post = Post.objects.get(id=post_id)
			return render(request, 'post.html', {'post': post, 'comments': comments, 'likes': likes})
		elif 'like_form' in request.POST:
			post = Post.objects.get(id=post_id)
			obj, created = Like.objects.get_or_create(img_id=post_id, login=login, post=post)
			if created == False:
				obj.delete()
				print("delete like")
			likes = Like.objects.all()
			comments = Comment.objects.all()
			return render(request, 'post.html', {'post': post, 'comments': comments, 'likes': likes})


def get_now():
	return datetime.now().strftime("%Y-%m-%d %H:%M:%S")

def add_comment(login, post_id, comment):
	post = Post.objects.get(id=post_id)
	comment = Comment.objects.update_or_create(img_id=post_id, login=login, comment=comment, post=post)[0]
	print(comment.id)
	print(comment.img_id)
	print(comment.comment)
	print(comment.postdate)
	print(comment.post.id)
	return comment

mysite/webcam/views.py
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse, HttpResponse
import json as simplejson
from .models import Post
from django.contrib.auth.models import User

from datetime import datetime

from PIL import Image
import base64
from io import BytesIO, StringIO
import re
# Create your views here.

def webcam(request):
	if request.is_ajax():
		data = request.POST
		if data["action"] == "merge":
			image = data["content"]
			imagedata = re.sub('^data:image/.+;base64,', '', image)
			imagedata += '=' * (-len(imagedata) % 4)
			imagedata = Image.open(BytesIO(base64.b64decode(imagedata)))
			imagedata = imagedata.convert('L')
			## testing 
			# imagedata.save("test.png")
			buffered = BytesIO()
			imagedata.save(buffered, format="PNG")
			encodeimg = "data:image/png;base64," + base64.b64encode(buffered.getvalue()).decode()
			
			# test
			# testimg = re.sub('^data:image/.+;base64,', '', encodeimg)
			# testimg = Image.open(BytesIO(base64.b64decode(testimg)))
			# testimg.save("re.png")
			context = {"finish" : encodeimg}
			return JsonResponse(context, safe=False)

		else:
			username = request.user.username
			add_post(username, data["content"])
			buffered = BytesIO()
			# context = {"stored" : buffered}
			context = {}
			return JsonResponse(context, safe=False)
	else :
		print("inside webcam()")
		return render(request, 'webcam.html')

def get_now():
	return datetime.now().strftime("%Y-%m-%d %H:%M:%S")
		

def add_post(login, image): 
	post = Post.objects.update_or_create(login=login, image=image, postdate=get_now())[0]
	print(post.id)
	print(post.login)
	print(post.postdate)
	return post

mysite/templates/base.html
<!-- templates/base.html -->
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<link rel="FaviconIcon" href="favicon.ico" type="image/x-icon">
	<link rel="stylesheet" type="text/css" href="{% static 'css/navbar.css' %}"></script>
</head>
<body>

  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

mysite/templates/home.html
{% load staticfiles %}

{% block content %}
<!doctype html>
<html>
<head>
	<link rel="FaviconIcon" href="favicon.ico" type="image/x-icon">
	<title>Camagru</title>
	<meta charset='utf-8'>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
	<script src="{% static 'js/delete.js' %}" type="text/javascript"></script>
	<link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}"></script>
	<link rel="stylesheet" type="text/css" href="{% static 'css/navbar.css' %}"></script>
	<link rel="stylesheet" type="text/css" href="{% static 'css/button.css' %}"></script>

</head>

{% if user.is_authenticated %}
<div class="topnav">
	<a class="active" href="#">Camagru</a>
	<a href="{% url 'home' %}">Home</a>
	<a href="{% url 'logout' %}">Logout</a>
	<a href="{% url 'webcam:webcam' %}">Post Pictures</a>
	</div>
	<h1>Hi {{ user.username }}!</h1>
	<div class="row">
	{% for post in posts %}
		<div>
				<div class="column">
			<div class="post_info">
			{{ post.id }}
			{{ post.login }}
		
			<br>
			<a href="{% url 'post:post' post.id %}">
				<img src="{{ post.image }}">
			</a>
		</div>
			<form action="/" method="post">
				{% csrf_token %}
				<input type="hidden" name="post_id" value="{{post.id}}" />
				<input type="submit" value="delete post" class="likeButton">
			</form>
			</div>
		</div>
	{% endfor %}
	</div>

	{% if messages %}
	<ul class="messages">
		{% for message in messages %}
		<li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
		{% endfor %}
	</ul>
{% endif %}
{% else %}
	<div class="topnav">
		<a class="active" href="#">Camagru</a>
		<a href="{% url 'home' %}">Home</a>
		<a href="{% url 'login' %}">Login</a>
		<a href="{% url 'signup' %}">Signup</a>
	</div>

	<h1><p>You are not logged in</p></h1>
{% endif %}
{% endblock %}

mysite/templates/post.html
{% load staticfiles %}

{% block content %}
<head>
	<link rel="stylesheet" type="text/css" href="{% static 'css/navbar.css' %}"></script>
	<link rel="stylesheet" type="text/css" href="{% static 'css/post.css' %}"></script>
	<link rel="stylesheet" type="text/css" href="{% static 'css/button.css' %}"></script>
</head>
<body background-color="lightblue">

<div class="topnav">
	<a class="active" href="#">Camagru</a>
	<a href="{% url 'home' %}">Home</a>
	<a href="{% url 'webcam:webcam' %}">Post Pictures</a>
	<a href="{% url 'logout' %}">Logout</a>
</div>
{% if user.is_authenticated %}
<center>
	<div class="box">
		{{ post.id }}
		{{ post.login }}
		<br>
		<img src="{{ post.image }}">
	</div>
	<form action="{% url 'post:post' post.id %}" method="post">
		{% csrf_token %}
			<input type="submit" value="like" name ="like_form" class="likeButton">
	</form>
	<form action="{% url 'post:post' post.id %}" method="post">
		{% csrf_token %}
			Comment:
			<input type="hidden" name="post_id" value="{{post.id}}" />
			<input type="text" name="comment">
			<input type="submit" value="submit" name ="comment_form" class="commentButton">
	</form>
	{% for like in likes %}
		
		{% if like.post_id == post.id %}
		Like: 
			{{ like.login }}
			
			<br>
		{% endif %}
	{% endfor %}	
	{% for comment in comments %}
		{% if comment.post_id == post.id %}
			
			{{ comment.login }}: {{ comment.comment }}
			
			<br>
		{% endif %}
	{% endfor %}
</center>
{% else %}
	<p>You are not logged in</p>
	<a href="{% url 'login' %}">login</a>
	<a href="{% url 'signup' %}">signup</a>
{% endif %}
</body>
{% endblock %}

mysite/templates/webcam.html
{% load staticfiles %}

{% block content %}
{% if user.is_authenticated %}

<!doctype html>
<html>
<head>
		<link rel="FaviconIcon" href="favicon.ico" type="image/x-icon">
	<title>Webcam</title>
	<meta charset='utf-8'>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
	<script src="{% static 'js/capture.js' %}" type="text/javascript"></script>
	<script src="{% static 'js/upload.js' %}" type="text/javascript"></script>
	<script src="{% static 'js/filter.js' %}" type="text/javascript"></script>
	<link rel="stylesheet" type="text/css" href="{% static 'css/webcam.css' %}"></script>
	<link rel="stylesheet" type="text/css" href="{% static 'css/navbar.css' %}"></script>
	<link rel="stylesheet" type="text/css" href="{% static 'css/button.css' %}"></script>
</head>
<body >
	<div class="topnav">
		<a class="active" href="#">Camagru</a>
		<a href="{% url 'home' %}">Home</a>
		<a href="{% url 'logout' %}">Logout</a>
	</div>
<center>
<!-- <div class="contentarea"> -->
	<h1>Take a Photo & Upload</h1>

<div class="box">
  <div class="camera">
    <video id="video">Video stream not available.</video>
		<button id="startbutton">Take photo</button> 
	</div>
	<canvas id="canvas">
		</canvas>
	<div class="output">
		<img id="photo" alt="The screen capture will appear in this box.">
	</div>
</div>
<br>
	

	<div id="pick-image">
		<form runat="server">
			<input type='file' accept="image/*" id="imgInp" />
		</form>
	</div>


	<div class="rex">
		<button id="clearbutton" class="myButton">Clear photo</button> 

		<button id="merge" class="myButton">Merge</button>

		<button id="post" class="myButton">Post</button>
	</div>
<!-- </div> -->
<!-- <img src="{% static 'images/wow.png' %}" alt="wow sticker" height="42" width="42">
<img src="{% static 'images/surprise.png' %}" alt="surprise sticker" height="42" width="42">
<img src="{% static 'images/pig.png' %}" alt="pig sticker" height="42" width="42">
<img src="{% static 'images/brainfuck.png' %}" alt="brainfuck sticker" height="42" width="42"> -->
<br>

</body>

<div class="footer">
	<i class="far fa-copyright"> 2019 Jeff Ding</i>
</div>
</center>
</html>
{% else %}
<p>You are not logged in</p>
<a href="{% url 'login' %}">login</a>
<a href="{% url 'signup' %}">signup</a>
{% endif %}
{% endblock %}